/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ad6edeac-3eed-44dd-94ad-87b08a95837f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wbWKXu6Hg",
    "aws_user_pools_web_client_id": "76jicl9ge07cs6tqod3is5o6pg",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://7ahgd4acuje7hiz5dplpxbbhwq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-uwmy5ukbyvginkqrps2h57ebny",
    "aws_user_files_s3_bucket": "amplifyapppedros14950-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
